### ISSUE TITLE
pytest-pep8 won't install with Python 3.7

### ISSUE THREAD

**Issue by phobson** [conda-forge/pytest-pep8-feedstock#8] opened 2019-10-21 18:13 UTC
Revisiting #6 

Issue:
A new conda-forge-only environment via `conda create --name=pep8test python=3.7 pytest-pep8 --channel=conda-forge` fails due to conflict.

I thought #7 would freshen up the build enough, but it's still hung up.

<br/>
Conda install log:
<details>

```
$ conda create --name=pep8test python=3.7 pytest-pep8 --channel=conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done                                                                                   failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Finding shortest conflict path for python:  75%|██████████████████████████████████████████              | 6/8 [00:00<00:00, 19.28it/s]Finding shortest conflict path for pip: 100%|███████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.54it/s]

Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
pytest-pep8 -> pytest[version='>=2.4.2'] -> setuptools[version='>=40.0']
Package wheel conflicts for:
python=3.7 -> pip -> wheel
pytest-pep8 -> python=3.4 -> pip -> wheel
Package pip conflicts for:
python=3.7 -> pip
pytest-pep8 -> python=3.4 -> pip
Package python conflicts for:
pytest-pep8 -> pytest[version='>=2.4.2'] -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
pytest-pep8 -> python[version='2.7.*|3.4.*|3.5.*']
pytest-pep8 -> pytest[version='>=2.4.2'] -> more-itertools[version='>=4.0'] -> python[version='>=3.4']
python=3.7
Package ca-certificates conflicts for:
pytest-pep8 -> pytest[version='>=2.4.2'] -> setuptools -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
Package apipkg conflicts for:
pytest-pep8 -> pytest-cache -> execnet[version='>=1.1.dev1'] -> apipkg[version='>=1.4']
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
Note that strict channel priority may have removed packages required for satisfiability.

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

WSL Ubuntu 18.04 LTS

<details>

```
$ conda info

     active environment : base
    active env location : /home/paul/miniconda3
            shell level : 1
       user config file : /home/paul/.condarc
 populated config files : /home/paul/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /home/paul/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/paul/miniconda3/pkgs
                          /home/paul/.conda/pkgs
       envs directories : /home/paul/miniconda3/envs
                          /home/paul/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.4.0-17134-Microsoft ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by phobson** [comment] 2019-11-07 02:27
I think I figured this out. Conda-forge's pytest-cache has been archived and not updated since July 2018.

Since I had my channel_priority set to strict, there's no long a conda-forge-only solution that works.

Removing the strict channel priority from .condarc allowed conda to pull pytest-cache from defaults and now things seem to be honky-dory

**Comment by nicoddemus** [comment] 2019-11-07 12:53
@phobson great you found the cause of the problem!

Should this be closed now?

**Comment by phobson** [comment] 2019-11-07 21:02
@nicoddemus I think so. In meantime, may I ask why conda-forge's pytest-cache has been archived? Can we reopen that?

**Comment by nicoddemus** [comment] 2019-11-07 21:46
I'm not sure myself @phobson, perhaps someone from @conda-forge/core can shed some light here?

Closing then, thanks!

**Closed as completed by nicoddemus** 2019-11-07 21:46 UTC

**Comment by ocefpaf** [comment] 2019-11-08 12:33
> @nicoddemus I think so. In meantime, may I ask why conda-forge's pytest-cache has been archived? Can we reopen that?

I don't recall why it was archived. We can restore and update it. Let me check...

**Comment by nicoddemus** [comment] 2019-11-08 13:09
> I think I figured this out. Conda-forge's pytest-cache has been archived and not updated since July 2018.

Wait, I thought this meant the *package* also did not exist on conda-forge anymore, but this is not the case:

https://anaconda.org/conda-forge/pytest-cache/files

Looking at the list of files, it is clear that we don't have a py37 version of pytest-cache. 

https://bitbucket.org/hpk42/pytest-cache is no longer maintained, that's why `conda-forge/pytest-cache-feedstock` was archived.

Being archived, it means it won't receive "rebuild for py*" updates from the bot (which probably didn't exist by the time `conda-forge/pytest-cache-feedstock` was archived).

Btw @phobson, pytest-pep8 seems mostly abandoned, I wouldn't recommend using it, but otherwise seems like pytest-pep8 should depend on later pytest versions (at least >=2.8), which has integrated cache support.

**Comment by CJ-Wright** [comment] 2019-11-08 15:14
@nicoddemus would you be interested in putting in some docs about what archived means?

**Comment by nicoddemus** [comment] 2019-11-11 23:05
@CJ-Wright sure, will be happy to.
